import { useUser } from "@clerk/nextjs/dist/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { ProductView } from "~/components/ProductView";
import { api } from "~/utils/api";
import { seedstores } from "~/utils/createStore";
import { scrapeWebsiteShopify, testFx } from "~/utils/scrapeWebsite";

export function getStaticProps() {
  void seedstores();
  console.log("get XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
  return { props: { x: 1 } };
}

const ProductsList = () => {
  const { data, isLoading: productFetching } = api.products.getAll.useQuery();

  if (!data) return <div>No se encontraron productos!</div>;

  return (
    <div>
      {data.map((product) => (
        <ProductView {...product} key={product.id} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  // getStaticProps();
  // Consigo el contexto de todo (DB, productos y SignIn)
  const ctx = api.useContext();

  // Consigo el usuario esta logeado y si ha cargado con Clerk
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  // Fetch lo antes posible

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#000000] to-[#eeeeee]">
        <ProductsList />
      </main>
    </>
  );
};

export default Home;
